version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-this
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    volumes:
      - ./backend:/app
    networks:
      - todo-network
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge
